2013/11/05 16:03:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(History))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(122): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/history
---
2013/11/05 16:03:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:03:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:03:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:03:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:03:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:03:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:03:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(History))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(122): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/history
---
2013/11/05 16:03:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(History))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(122): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/history
---
2013/11/05 16:03:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:03:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:03:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:03:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:03:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:04:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(History))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(122): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/history
---
2013/11/05 16:04:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:04:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:04:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:04:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:04:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(History))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(122): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/history
---
2013/11/05 16:04:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:04:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:04:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Threats))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(128): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/05 16:04:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(History))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(122): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/history
---
2013/11/05 16:04:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 5432?' in /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(2374): CActiveRecord->getDbConnection()
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(History))
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(122): CActiveRecord->__construct()
#9 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#10 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#14 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#15 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/history
---
2013/11/06 20:36:28 [error] [exception.CException] exception 'CException' with message 'Property "Services.service_id" is not defined.' in /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('service_id')
#1 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(197): CActiveRecord->__get('service_id')
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#8 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/06 20:47:09 [error] [exception.CException] exception 'CException' with message 'Property "Services.service_id" is not defined.' in /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('service_id')
#1 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(197): CActiveRecord->__get('service_id')
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#8 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/06 20:47:11 [error] [exception.CException] exception 'CException' with message 'Property "Services.service_id" is not defined.' in /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('service_id')
#1 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(197): CActiveRecord->__get('service_id')
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#8 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/06 20:47:11 [error] [exception.CException] exception 'CException' with message 'Property "Services.service_id" is not defined.' in /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('service_id')
#1 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(197): CActiveRecord->__get('service_id')
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#8 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/06 20:47:11 [error] [exception.CException] exception 'CException' with message 'Property "Services.service_id" is not defined.' in /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('service_id')
#1 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(197): CActiveRecord->__get('service_id')
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#8 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/06 20:47:11 [error] [exception.CException] exception 'CException' with message 'Property "Services.service_id" is not defined.' in /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('service_id')
#1 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(197): CActiveRecord->__get('service_id')
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#8 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
2013/11/06 20:47:11 [error] [exception.CException] exception 'CException' with message 'Property "Services.service_id" is not defined.' in /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Users/dani/Dev/TGD/src/webapp/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('service_id')
#1 /Users/dani/Dev/TGD/src/webapp/TGD/protected/controllers/ApiController.php(197): CActiveRecord->__get('service_id')
#2 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/actions/CInlineAction.php(49): ApiController->actionCreate()
#3 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#7 /Users/dani/Dev/TGD/src/webapp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('api/create')
#8 /Users/dani/Dev/TGD/src/webapp/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /Users/dani/Dev/TGD/src/webapp/TGD/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/TGD/src/webapp/TGD/api/threats
---
